### PR TITLE
Fix free OS check issue

### PR DESCRIPTION
**Pull request by cybercop23**
fix in 6.1 branch so users can upgrade before next master realease

### CODE REVIEW

**Comment by Poporacer** [comment]
This was already implemented in the Master Branch

**Comment by cybercop23** [comment]
Yes, but this is needed so users that are on 6.1 can upgrade OS from the About menu. Right now they are stuck and won't be able to ever use that. They'l have to manually download and install via the Content/File Manager.

**Comment by Poporacer** [comment]
The next release, 6.1.1 will be a minor release which will not require an OS upgrade, just a normal FPP Upgrade and will fix the OS Upgrade button issue.

**Comment by Poporacer** [comment]
Implemented in version 6.1.1

**Pull request closed without merging**
