### PR TITLE
Changed relative to absolute URL for crash reports

### PR DESCRIPTION
**Pull request by MrPaulAR**
Fixes https://github.com/FalconChristmas/fpp/issues/1609

### CODE REVIEW

**Comment by dkulp** [comment]
If the FPP instance is behind a proxy FPP instance, the warning then displayed on the main status page would not work.   That's the main reason for using the relative URL.

**Comment by MrPaulAR** [comment]
That makes sense on the API endpoint.

Going back to the issue for this PR, how can I address that?  I don't think
editing the multisync.php page will be aware of the proxy either (consider
I can run this on any FPP instance...not just the one doing the proxy).
Right now, the only time the crash url works in the multisync.php output is
if I'm on that device device.

**Comment by dkulp** [comment]
My gut feeling is that it should be relative, but add something like class="localWarningLink" and then use some javascript or something on the multisync page to replace the URL's that have that class.

**Comment by MrPaulAR** [comment]
JavaScript is beyond my current skillset that I'm comfortable showing to
others.  The PHP touched my old perl stuff...mostly python now.

I'm gonna close this pull request and maybe someone else will pick up the
issue.  It's cosmetic only so not a big deal if not.

**Pull request closed without merging**
