### PR TITLE
Multiple UI updates jquery/bootstrap jquery-ui and assoc plugins + new tabbed troubleshooting page and a few display improvements

### PR DESCRIPTION
**Pull request by OnlineDynamic**
Minor version uplifts on UI components 

- bootstrap
- jquery
- filepond
- tablesorter
- jcanvas
- jquery-form
- fabric
- timepicker
- sheetjs
 
troubleshooting page updated to group commands in new bootstrap layout and run off a json config file with titles, descriptions, platform relevance flags etc..

a couple of fixes to UI display code:
- fix for healthchecker on firefox
- fixed showing media dir status on helthchecker
- remove redundant code on help pages

misc:
- copyright dates update
- git info added on troubleshooting page
-

### CODE REVIEW

**Comment by cpinkham** [comment]
The update to the timepicker file reverts a local mod we have been running (example in f6b4b23f41d4b) to allow midnight to appear at both the bottom and top of the list.  Can you re-apply that on top of the update to timepicker 1.14.1?  I'm not sure if that is something upstream would be interested in or not.  I don't know of any other local mods we have, I spotchecked multiple files and directories looking for commits that weren't version updates and didn't see any.

**Comment by OnlineDynamic** [comment]
@cpinkham good spot! I have patched that FPP Mod back into the timepicker.js with latest commit in this PR

**Comment by darylc** [comment]
In future can you log individual pull requests for unrelated changes?  I'd be happy to review (and likely accept) your changes to the troubleshooting page, but I am not am expert in all the unrelated UI version changes.

**Comment by OnlineDynamic** [comment]
> In future can you log individual pull requests for unrelated changes? I'd be happy to review (and likely accept) your changes to the troubleshooting page, but I am not am expert in all the unrelated UI version changes.

will do but was trying to test my changes against the new UI component changes as I was testing it all through..
@cpinkham @darylc can one of you please merge the PR

**Comment by OnlineDynamic** [comment]
@darylc have added your SMART commands to the JSON and matched your output width (I had already increased it but not by as much as you)

**Comment by darylc** [comment]
I'm hesitant to accept this pull request personally due to it touching areas I am not familiar with, I'd prefer @cpinkham to review it.  I just wanted to point out that right now it has a conflict on www/troubleshootingHelper.php that stops it from being merged.

**Comment by OnlineDynamic** [comment]
I am going to split this PR to make life easier and then will close this one

**Pull request closed without merging**
