### PR TITLE
Added the possibility to keep the last state after an effect is played

### PR DESCRIPTION
**Pull request by Sven-v-Beuningen**
To allow some more flexibility in playing effects, I added the possibility to control whether the channel should be blanked after the effect is ended, or not.

### CODE REVIEW

**Comment by cpinkham** [comment]
Can you update this patch and pull request to be based against the current FPP master branch and then we can get it merged into FPP?

**Comment by Sven-v-Beuningen** [comment]
I did the update of the pull request, but **I wasn't able to provide the new binaries**. I tried to build them on my BBB, but I've got some compilation errors, which doesn't seem to be related to my change.

E.g. 
`In file included from channeloutput/channeloutput.c:88:0:
channeloutput/OLAOutput.h:37:7: note:   because the following virtual functions are pure within ‘OLAOutput’:
 class OLAOutput : public ThreadedChannelOutputBase {
`

**Comment by patdelaney** [comment]
What is the purpose for this ? Does it need to be documented for the end
users?

Thanks

**Comment by Sven-v-Beuningen** [comment]
The current behavior is, that all channels are blanked out, after an effect is played. This makes it hard to fade in some channels and just keep them as they are at the end of the effect. E.g. just to turn on or off some permanent illumination with a nice effect.
This pull request adds an optional flag to the effects to just not blank out the channels after the effect has ended.

**Comment by cpinkham** [comment]
Don't worry about binaries, we will test compiling and check into this
issue.  We don't include binaries in the repository anymore with FPP
v2.x.

On Sat, 2018-12-15 at 14:07 -0800, Sven-v-Beuningen wrote:
> > > I did the update of the pull request, but I wasn't able to provide
the new binaries. I tried to build them on my BBB, but I've got some
compilation errors, which doesn't seem to be related to my change.
> E.g.
> 
> > > > In file included from channeloutput/channeloutput.c:88:0:
channeloutput/OLAOutput.h:37:7: note:   because the following virtual
functions are pure within ‘OLAOutput’: class OLAOutput : public
ThreadedChannelOutputBase { 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> > > > > > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/FalconChr
istmas/fpp","title":"FalconChristmas/fpp","subtitle":"GitHub
repository","main_image_url":"https://github.githubassets.com/images/
email/message_cards/header.png","avatar_image_url":"https://github.gi
thubassets.com/images/email/message_cards/avatar.png","action":{"name
":"Open in
GitHub","url":"https://github.com/FalconChristmas/fpp"}},"updates":{"
snippets":[{"icon":"PERSON","message":"@Sven-v-Beuningen in #379: I
did the update of the pull request, but **I wasn't able to provide
the new binaries**. I tried to build them on my BBB, but I've got
some compilation errors, which doesn't seem to be related to my
change.\r\n\r\nE.g. \r\n`In file included from
channeloutput/channeloutput.c:88:0:\r\nchanneloutput/OLAOutput.h:37:7
: note:   because the following virtual functions are pure within
‘OLAOutput’:\r\n class OLAOutput : public ThreadedChannelOutputBase
{\r\n`"}],"action":{"name":"View Pull Request","url":"https://github.
com/FalconChristmas/fpp/pull/379#issuecomment-447601159"}}}
> [
> {
> > "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> > "target": "https://github.com/FalconChristmas/fpp/pull/379#issuecomme
nt-447601159",
> > "url": "https://github.com/FalconChristmas/fpp/pull/379#issuecomment-
447601159",
> "name": "View Pull Request"
> },
> "description": "View this Pull Request on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> > "url": "https://github.com"
> }
> }
> ]

**Comment by patdelaney** [comment]
Where would that setting be stored?

**Comment by Sven-v-Beuningen** [comment]
It is stored at the fppeffect struct. Together with "loop" and "startChannel".

**Comment by cpinkham** [comment]
This issue was fixed in 2019, FPP should not blank out channel data when an effect ends.  Closing ticket.

**Pull request closed without merging**
