### PR TITLE
[Enhancement] Backup/Restore Settings feature

### LINKED ISSUE #114: Enhancement: Export / Import Email settings
As a user I would like the ability to Export Email settings and be able to import it on to another FPP.
I have 6 FPP and I don't want to have to type the email configs over again on each unit.

Thanks

### LINKED ISSUE #146: Enhancement: Add the ability to backup and restore configuration files
As a QA tester it would be a lot easier to test different scenarios as well as troubleshoot other user's issues if there was a way to back and restore system configurations.

For Example: I may want to test different matrix configurations and I want to "backup" the current configuration so I can restore it at a later date.
The backup should include:
channelmemorymaps
channeloutputs
schedule
settings
timezone
universes
the /fpp/media/config directory or just channeloutputs.json file

### PR DESCRIPTION
**Pull request by jaredb7**
As requested by patdelaney #146  , to have a system were settings can be backed up and restored for QA testing.

The system I created is based around 'areas', which is basically the different settings areas of the FPP system.  Main settings, email, schedule, channel outputs etc..

You can opt to backup everything by selecting 'All' when backing up, or a specific setting eg. RGBMatrix. Chosen settings are collected into a json encoded file for download. 
A copy of the backup is also left in /media/config, possible future feature is restore from these removing the need to upload any backups

Backup files are named < host >-< setting_area >_date&time.json.

Restoration works the same way, choose a area to restore, choose the file json file.
When restoring the script will just look for a existence of that area key in the uploaded file. So you can't upload settings into wrong areas
You can use the full/all backup and selectively restore other settings from it, eg restore the schedule only out of a full backup.

If a setting change would normally cause some other shell command to also be run (PI_LCD, piRTC, NTP) ect when changing it from the GUI, this script will also make calls to those functions to try keep things in line.

Some helper functions have been added to common.php, some code moved out of specific php files and into common.php to try and reduce code duplication or be able to access specific code blocks for setting restores.

Some features I hope to implement in the future:
*Backup of events, scripts and playlists
*Backup of plugin settings?
*Backup of WLAN interface settings ?
*Restore from backups stored on device
*Change logging (new and old value of setting where applicable)

Caveats:
Standalone email setting backup doesn't include password as it's being "nulled" out for security (I just read the global variables and its also taboo in the ReadSettings function), full or settings backups include this the entire settings file is read by bypassing the ReadSettings function.

closes #146
closes #114 

backup
backup_area_selection
backup_settings
backup_files

### CODE REVIEW

**Comment by cpinkham** [comment]
Do you know if this works with current master?  I'd like to get this merged in before the FPP v1.5 release, I didn't realize it was this far along.  Thanks for the work, I'm sure it will be much appreciated.

**Comment by jaredb7** [comment]
Yes it does work with the current master (v1.5-pre38). I made a tiny change tonight to fix some small issues I found while testing it out.

**Comment by jaredb7** [comment]
This isn't ready to merge after the commit c1d7e22e1c378907f2cd3f0bbd1905ebcb831dce . I had previously made changes to time.php where I refactored the enable and disable ntp code into a function in common.php and just need to update this and refactor out the ntpServer setting commands.


I have an additional commit coming up to enable users to export sensitive data like passwords for direct cloning FPP's, by default none of this data will exported in attempt to prevent data leakage. 
And to add support for ntpServer setting restoration.

**Comment by jaredb7** [comment]
This is right to merge in now.

**Comment by cpinkham** [comment]
Thanks for updating, I will try to get this into master and stage in the next couple days.

Do you think you could make it backup/restore playlists as well? Users will have their media and sequences elsewhere, but their playlists are like schedules and created within FPP. It would be good if we could have several sub-directories backed up somehow:

- playlists
- events
- scripts

Playlists and events are obviously created on FPP, but scripts may be downloaded from the Script repo and then editted, so it would be good to back those up as well.

**Comment by jaredb7** [comment]
That shouldn't be a problem, I started work on it last night and have it backing up those folders and file within, when I get some more time I'll finish it up which should be in the next day or so.

**Comment by jaredb7** [comment]
Added support to backup and restore Playlists, Events and Scripts, theses along with Schedules are bundles together in the "Show Setup" backup.

fpp_show_setup_backup
fpp_show_setupcapture

**Pull request merged**
